# Dataset - DataFrame

### 1. Preparar el entorno e importar la clase de carga
El notebook puede ejecutarse desde distintas carpetas. Por eso se buscan los directorios padres hasta encontrar src/clases_po y se agrega src a sys.path. Así se puede importar HFDatasetLoader sin instalar el proyecto como paquete.

In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().resolve()
while ROOT != ROOT.parent and not (ROOT / "src" / "clases_po").exists():
    ROOT = ROOT.parent

sys.path.insert(0, str(ROOT / "src"))

from clases_po import HFDatasetLoader

/home/runner/work/Machine_Learning/Machine_Learning/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### 2. Configurar el dataset y la salida
dataset_name identifica el repositorio en Hugging Face y split="train" indica la división que se descargará. El parámetro filename hace que el DataFrame también se guarde como CSV en src/carga_datos/datos/ cuando el notebook se ejecuta desde esa carpeta.

In [2]:
loader = HFDatasetLoader(
    dataset_name="mstz/heart_failure",
    split="train",
    filename="datos/heart_failure.csv",
)

### 3. Descargar el dataset y crear el DataFrame
El método load() descarga el dataset, lo convierte a pandas.DataFrame y lo asigna a la variable df. La expresión df.head() muestra las primeras filas para comprobar que la carga fue exitosa.

In [3]:
df = loader.load()
df.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Generating train split:   0%|          | 0/299 [00:00<?, ? examples/s]

Generating train split: 100%|██████████| 299/299 [00:00<00:00, 72680.20 examples/s]

,age,has_anaemia,creatinine_phosphokinase_concentration_in_blood,has_diabetes,heart_ejection_fraction,has_high_blood_pressure,platelets_concentration_in_blood,serum_creatinine_concentration_in_blood,serum_sodium_concentration_in_blood,is_male,is_smoker,days_in_study,is_dead
0,75,False,582.0,False,20.0,True,265000.00,1.9,130.0,True,False,4,1
1,55,False,7861.0,False,38.0,False,263358.03,1.1,136.0,True,False,6,1
2,65,False,146.0,False,20.0,False,162000.00,1.3,129.0,True,True,7,1
3,50,True,111.0,False,20.0,False,210000.00,1.9,137.0,True,False,7,1
4,65,True,160.0,True,20.0,False,327000.00,2.7,116.0,False,False,8,1

### 4. Revisar la estructura del DataFrame
Esta celda realiza una revisión inicial: cuenta filas y columnas y muestra el tipo de cada columna junto con información de memoria y valores no nulos. Esta inspección ayuda a detectar problemas antes de analizar los datos.

In [4]:
print(f"Filas: {len(df)}")
print(f"Columnas: {len(df.columns)}")
df.info()

Filas: 299
Columnas: 13
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   age                                              299 non-null    int64
 1   has_anaemia                                      299 non-null    bool
 2   creatinine_phosphokinase_concentration_in_blood  299 non-null    float64
 3   has_diabetes                                     299 non-null    bool
 4   heart_ejection_fraction                          299 non-null    float64
 5   has_high_blood_pressure                          299 non-null    bool
 6   platelets_concentration_in_blood                 299 non-null    float64
 7   serum_creatinine_concentration_in_blood          299 non-null    float64
 8   serum_sodium_concentration_in_blood              299 non-null    float64
 9   is_male                                          299 non-null    bool
 10  is_smoker                                        299 non-null    bool
 11  days_in_study                                    299 non-null    int64
 12  is_dead                                          299 non-null    int64
dtypes: bool(5), float64(5), int64(3)
memory usage: 20.3 KB

# Reporte

### 5. Importar la clase de reportes
Reportes recibe un DataFrame en sus métodos y permite generar un resumen textual, imprimirlo en la consola o guardarlo en un archivo .txt.

In [5]:
from clases_po import Reportes

### 6. Generar y visualizar el reporte como texto
generar_reporte(df) devuelve un str con el número de filas, columnas, duplicados, tipos de datos, valores nulos y estadísticas numéricas. En esta celda el texto se guarda temporalmente en texto y se imprime.

In [6]:
reportes = Reportes()
texto = reportes.generar_reporte(df)

print(texto)

REPORTE DEL DATAFRAME
============================================================
Filas: 299
Columnas: 13
Duplicados: 0

Columnas y tipos:
- age: int64
- has_anaemia: bool
- creatinine_phosphokinase_concentration_in_blood: float64
- has_diabetes: bool
- heart_ejection_fraction: float64
- has_high_blood_pressure: bool
- platelets_concentration_in_blood: float64
- serum_creatinine_concentration_in_blood: float64
- serum_sodium_concentration_in_blood: float64
- is_male: bool
- is_smoker: bool
- days_in_study: int64
- is_dead: int64

Valores nulos por columna:
- age: 0
- has_anaemia: 0
- creatinine_phosphokinase_concentration_in_blood: 0
- has_diabetes: 0
- heart_ejection_fraction: 0
- has_high_blood_pressure: 0
- platelets_concentration_in_blood: 0
- serum_creatinine_concentration_in_blood: 0
- serum_sodium_concentration_in_blood: 0
- is_male: 0
- is_smoker: 0
- days_in_study: 0
- is_dead: 0

Estadísticas numéricas:
           age  creatinine_phosphokinase_concentration_in_blood  heart_ejection_fraction  platelets_concentration_in_blood  serum_creatinine_concentration_in_blood  serum_sodium_concentration_in_blood  days_in_study  is_dead
count  299.000                                          299.000                  299.000                           299.000                                  299.000                              299.000        299.000  299.000
mean    60.829                                          581.839                   38.084                        263358.029                                    1.394                              136.625        130.261    0.321
std     11.895                                          970.288                   11.835                         97804.237                                    1.035                                4.412         77.614    0.468
min     40.000                                           23.000                   14.000                         25100.000                                    0.500                              113.000          4.000    0.000
25%     51.000                                          116.500                   30.000                        212500.000                                    0.900                              134.000         73.000    0.000
50%     60.000                                          250.000                   38.000                        262000.000                                    1.100                              137.000        115.000    0.000
75%     70.000                                          582.000                   45.000                        303500.000                                    1.400                              140.000        203.000    1.000
max     95.000                                         7861.000                   80.000                        850000.000                                    9.400                              148.000        285.000    1.000

### 7. Imprimir el reporte directamente
imprimir_reporte(df) ejecuta la generación y muestra el resultado directamente. Es útil para consultar rápidamente el resumen durante una ejecución interactiva.

In [7]:
reportes.imprimir_reporte(df)

REPORTE DEL DATAFRAME
============================================================
Filas: 299
Columnas: 13
Duplicados: 0

Columnas y tipos:
- age: int64
- has_anaemia: bool
- creatinine_phosphokinase_concentration_in_blood: float64
- has_diabetes: bool
- heart_ejection_fraction: float64
- has_high_blood_pressure: bool
- platelets_concentration_in_blood: float64
- serum_creatinine_concentration_in_blood: float64
- serum_sodium_concentration_in_blood: float64
- is_male: bool
- is_smoker: bool
- days_in_study: int64
- is_dead: int64

Valores nulos por columna:
- age: 0
- has_anaemia: 0
- creatinine_phosphokinase_concentration_in_blood: 0
- has_diabetes: 0
- heart_ejection_fraction: 0
- has_high_blood_pressure: 0
- platelets_concentration_in_blood: 0
- serum_creatinine_concentration_in_blood: 0
- serum_sodium_concentration_in_blood: 0
- is_male: 0
- is_smoker: 0
- days_in_study: 0
- is_dead: 0

Estadísticas numéricas:
           age  creatinine_phosphokinase_concentration_in_blood  heart_ejection_fraction  platelets_concentration_in_blood  serum_creatinine_concentration_in_blood  serum_sodium_concentration_in_blood  days_in_study  is_dead
count  299.000                                          299.000                  299.000                           299.000                                  299.000                              299.000        299.000  299.000
mean    60.829                                          581.839                   38.084                        263358.029                                    1.394                              136.625        130.261    0.321
std     11.895                                          970.288                   11.835                         97804.237                                    1.035                                4.412         77.614    0.468
min     40.000                                           23.000                   14.000                         25100.000                                    0.500                              113.000          4.000    0.000
25%     51.000                                          116.500                   30.000                        212500.000                                    0.900                              134.000         73.000    0.000
50%     60.000                                          250.000                   38.000                        262000.000                                    1.100                              137.000        115.000    0.000
75%     70.000                                          582.000                   45.000                        303500.000                                    1.400                              140.000        203.000    1.000
max     95.000                                         7861.000                   80.000                        850000.000                                    9.400                              148.000        285.000    1.000

### 8. Guardar el reporte en un archivo de texto
guardar_reporte(df, ruta) crea los directorios necesarios y escribe el reporte en UTF-8. El archivo quedará en src/sincronicas/reportes/fast_food_restaurants.txt cuando se ejecute desde src/sincronicas.

In [ ]:
ruta = reportes.guardar_reporte(
    df,
    "reportes/heart_failure.txt",
)

print(f"Reporte guardado en: {ruta}")

Reporte guardado en: reportes/fast_food_restaurants.txt

# Transformaciones

### 9. Transformación 1: Traducir y estandarizar nombres de columnas
Se renombran las 13 columnas del DataFrame de inglés a español manteniendo el formato `snake_case` para mejorar la legibilidad del análisis.

In [9]:
# Diccionario de traducción de columnas
columnas_espanol = {
    'age': 'edad',
    'has_anaemia': 'tiene_anemia',
    'creatinine_phosphokinase_concentration_in_blood': 'cpk_sangre',
    'has_diabetes': 'tiene_diabetes',
    'heart_ejection_fraction': 'fraccion_eyeccion',
    'has_high_blood_pressure': 'tiene_hipertension',
    'platelets_concentration_in_blood': 'concentracion_plaquetas',
    'serum_creatinine_concentration_in_blood': 'creatinina_serica',
    'serum_sodium_concentration_in_blood': 'sodio_serico',
    'is_male': 'es_hombre',
    'is_smoker': 'es_fumador',
    'days_in_study': 'dias_seguimiento',
    'is_dead': 'fallecido'
}

# Aplicar el renombrado
df = df.rename(columns=columnas_espanol)

# Mostrar las primeras filas con los nuevos nombres
df.head()

,edad,tiene_anemia,cpk_sangre,tiene_diabetes,fraccion_eyeccion,tiene_hipertension,concentracion_plaquetas,creatinina_serica,sodio_serico,es_hombre,es_fumador,dias_seguimiento,fallecido
0,75,False,582.0,False,20.0,True,265000.00,1.9,130.0,True,False,4,1
1,55,False,7861.0,False,38.0,False,263358.03,1.1,136.0,True,False,6,1
2,65,False,146.0,False,20.0,False,162000.00,1.3,129.0,True,True,7,1
3,50,True,111.0,False,20.0,False,210000.00,1.9,137.0,True,False,7,1
4,65,True,160.0,True,20.0,False,327000.00,2.7,116.0,False,False,8,1

### 10. Transformación 2: Conversión de días a años de seguimiento
Se crea una nueva variable calculada dividiendo los días de seguimiento entre 365 para expresar el tiempo en años.

In [10]:
# Operación matemática directa sobre la columna
df['anos_seguimiento'] = (df['dias_seguimiento'] / 365).round(2)

# Mostrar resultado
df[['dias_seguimiento', 'anos_seguimiento']].head()

   dias_seguimiento  anos_seguimiento
0                 4              0.01
1                 6              0.02
2                 7              0.02
3                 7              0.02
4                 8              0.02

### 11. Transformación 3: Mapeo de valores a texto explícito
Se transforman las columnas de género y estado vital a texto claro (`Masculino/Femenino` y `Fallecido/Sobreviviente`) para facilitar la interpretación del dataset.

In [11]:
# Crear variables categóricas descriptivas usando .loc
df.loc[:, 'genero'] = df['es_hombre'].map({True: 'Masculino', False: 'Femenino'})
df.loc[:, 'estado_vital'] = df['fallecido'].map({1: 'Fallecido', 0: 'Sobreviviente'})

# Mostrar la comparación de las columnas transformadas
df[['es_hombre', 'genero', 'fallecido', 'estado_vital']].head()

   es_hombre     genero  fallecido estado_vital
0       True  Masculino          1    Fallecido
1       True  Masculino          1    Fallecido
2       True  Masculino          1    Fallecido
3       True  Masculino          1    Fallecido
4      False   Femenino          1    Fallecido

### 12. Transformación 4: Agrupamiento y resumen estadístico por grupo
Se agrupan los datos según el `estado_vital` del paciente para calcular los promedios de los principales biomarcadores clínicos.

In [12]:
# Agrupamiento por estado vital y cálculo de promedios
df_resumen = df.groupby('estado_vital').agg({
    'edad': 'mean',
    'fraccion_eyeccion': 'mean',
    'creatinina_serica': 'mean',
    'concentracion_plaquetas': 'mean'
}).rename(columns={
    'edad': 'Edad Promedio',
    'fraccion_eyeccion': 'Fracción Eyección (%)',
    'creatinina_serica': 'Creatinina Promedio',
    'concentracion_plaquetas': 'Plaquetas Promedio'
}).reset_index()

df_resumen

,estado_vital,Edad Promedio,Fracción Eyección (%),Creatinina Promedio,Plaquetas Promedio
0,Fallecido,65.208333,33.46875,1.835833,256381.044792
1,Sobreviviente,58.758621,40.26601,1.184877,266657.489901